### ISSUE TITLE
Temperature readout

### ISSUE THREAD

**Issue by Depechie** [pippocla/my_home#3]
Trying out this custom component and all the light elements work fine, thanks for this!
But the temperature sensors always give a keyerror in the HomeAssistant log.
Any idea what this should be?

Configuration:
```
sensor:
  - platform: my_home
    devices:
      - name: "Bedroom"
        indirizzo: '4'
```
Log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/my_home.py", line 95, in update
    self._state=self._gate.answ_read_temperature(self._indirizzo)
  File "/config/deps/lib/python3.7/site-packages/OpenWebNet.py", line 455, in answ_read_temperature
    valore = float(self.stato_answer('4',where,'0'))/10
  File "/config/deps/lib/python3.7/site-packages/OpenWebNet.py", line 409, in stato_answer
    return self.sensor_risposta[where]
KeyError: '4
```

**Comment by Depechie** [comment]
I'm not that adapt in python...
But OpenWebNet calls for Temperature and Lights are not the same.
Example call to readout my temperature through the OpenWebNet protocol should be:
`*#4*1*0##`
